version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: cp_user
      POSTGRES_PASSWORD: cp_pass
      POSTGRES_DB: cp_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cp_user"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  backend:
    build: ./changepreneurship-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+psycopg://cp_user:cp_pass@postgres:5432/cp_db
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: changepreneurship-dev-secret
      ALLOWED_ORIGINS: http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5000/api/health || curl -fsS http://localhost:5000/api/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

  frontend:
    build: ./changepreneurship-enhanced
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5173:80"
    environment:
      # For local dev hitting backend directly
      VITE_API_BASE: http://localhost:5000
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ | grep -qi '<html' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  pgdata: {}
