/**
 * AI Insights Page — Entrepreneur & Venture Report
 *
 * All scores, insights, sweet-spots, risk-zones and phase cards are
 * generated by Groq (llama-3.3-70b-versatile) via the backend endpoint
 * GET /api/ai/insights-report
 *
 * Nothing is hardcoded or deterministic — every number and insight
 * comes from the AI consensus response.
 */
import React, { useEffect, useRef, useState, useCallback } from "react";
import { Link, useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Brain,
  CheckCircle2,
  Sparkles,
  AlertTriangle,
  Lock,
  RefreshCw,
  Loader2,
} from "lucide-react";
import {
  Chart,
  Filler,
  Legend,
  LineElement,
  PointElement,
  RadarController,
  RadialLinearScale,
  Tooltip,
} from "chart.js";
import { Button } from "@/components/ui/button.jsx";
import apiService from "@/services/api.js";
import "./AIInsightsPage.css";

Chart.register(RadarController, RadialLinearScale, PointElement, LineElement, Filler, Tooltip, Legend);

// ---------------------------------------------------------------------------
// Static reference data (labels + benchmark lines only — no mock scores)
// ---------------------------------------------------------------------------
const ENT_LABELS = [
  "Motivation", "Personality", "Values", "Self-Awareness",
  "Life Support", "Resources", "Passion", "Skills",
  "Vision", "Leadership", "Team Building", "Culture",
];
const VEN_LABELS = [
  "Market Demand", "Problem-Solution Fit", "Business Model", "Strategic Thinking",
  "Positioning", "Customer Validation", "Competitive Analysis", "Market Sizing",
];
const AVG_FOUNDER  = [72, 70, 68, 65, 72, 70, 70, 68, 66, 62, 58, 60];
const AVG_VENTURE  = [62, 58, 60, 55, 56, 55, 52, 50];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const scoreColor = (s) => {
  if (s >= 80) return "#22c55e";
  if (s >= 65) return "#f97316";
  return "#ef4444";
};
const scoreClass = (s) => {
  if (s >= 80) return "green";
  if (s >= 65) return "orange";
  return "red";
};
const radarVals = (radarObj, labels) =>
  labels.map((l) => (radarObj && radarObj[l] != null ? radarObj[l] : 0));

const radarOptions = {
  responsive: true,
  plugins: { legend: { display: false } },
  scales: {
    r: {
      grid: { color: "rgba(255,255,255,0.06)" },
      angleLines: { color: "rgba(255,255,255,0.06)" },
      pointLabels: { color: "rgba(255,255,255,0.5)", font: { size: 9, family: "Inter" } },
      ticks: { display: false },
      suggestedMin: 0,
      suggestedMax: 100,
    },
  },
};

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

const MiniBar = ({ label, value, colorClass = "orange" }) => (
  <div className="ai7-mini-row">
    <span>{label}</span>
    <div className="ai7-mini-track">
      <div className={`ai7-fill-${colorClass}`} style={{ width: `${value}%` }} />
    </div>
    <strong style={{ color: scoreColor(value) }}>{value}</strong>
  </div>
);

const PhaseCard = ({ card, accent }) => (
  <div className="exp-card" style={{ borderColor: `${accent}20` }}>
    <div className="ec-top">
      <h4>{card.name}</h4>
      <span className={`ec-score ${scoreClass(card.score)}`}>{card.score}</span>
    </div>
    <div className="ec-bar">
      <div className="ec-fill" style={{ width: `${card.score}%`, background: scoreColor(card.score) }} />
    </div>
    <div className="ec-desc">{card.description}</div>
    {card.subs?.length > 0 && (
      <div className="ec-subs">
        {card.subs.map((s) => <MiniBar key={s.name} label={s.name} value={s.score} />)}
      </div>
    )}
  </div>
);

const ConnCard = ({ item, type }) => {
  const isPot = type === "potential";
  const leftLabel  = isPot ? "Your Strength" : "Entrepreneur";
  const rightLabel = isPot ? "Venture Gap"   : "Venture";
  const leftDim    = isPot ? item.strength_dim  : item.ent_dim;
  const leftScore  = isPot ? item.strength_score : item.ent_score;
  const rightDim   = isPot ? item.gap_dim   : item.ven_dim;
  const rightScore = isPot ? item.gap_score  : item.ven_score;
  return (
    <div className={`conn-card ${type === "potential" ? "potential" : type}`}>
      <div className="cc-row">
        <div className="cc-side">
          <div className="cc-tag orange">{leftLabel}</div>
          <div className="cc-dim">{leftDim}</div>
          <div className={`cc-score-val ${scoreClass(+leftScore || 0)}`}>{leftScore}</div>
        </div>
        <div className="cc-mid">
          <div className={`cc-connector ${type}`} />
          <div className={`cc-badge ${type}`}>{item.relation}</div>
        </div>
        <div className="cc-side" style={{ textAlign: "right" }}>
          <div className="cc-tag blue">{rightLabel}</div>
          <div className="cc-dim">{rightDim}</div>
          <div className={`cc-score-val ${typeof rightScore === "number" ? scoreClass(rightScore) : "orange"}`}>
            {rightScore}
          </div>
        </div>
      </div>
      <div className="cc-insight" dangerouslySetInnerHTML={{ __html: item.insight }} />
      {type === "risk" && item.action && (
        <div className="cc-action risk-btn">⚡ {item.action}</div>
      )}
    </div>
  );
};

const LoadingState = () => (
  <div className="ai7-page">
    <div className="ai7-bg" />
    <div className="ai7-container" style={{
      display: "flex", flexDirection: "column", alignItems: "center",
      justifyContent: "center", minHeight: "60vh", gap: 16
    }}>
      <Loader2 className="animate-spin" style={{ width: 40, height: 40, color: "#a855f7" }} />
      <h2 style={{ color: "#fff", fontSize: 20, fontWeight: 700 }}>AI is analyzing your assessment…</h2>
      <p style={{ color: "rgba(255,255,255,0.4)", fontSize: 13, textAlign: "center", maxWidth: 420 }}>
        Your responses from all phases are being sent to Groq LLM.<br />
        Generating entrepreneur &amp; venture insights report — this may take 10–20 seconds.
      </p>
    </div>
  </div>
);

const ErrorState = ({ message, onRetry }) => (
  <div className="ai7-page">
    <div className="ai7-bg" />
    <div className="ai7-container" style={{
      display: "flex", flexDirection: "column", alignItems: "center",
      justifyContent: "center", minHeight: "60vh", gap: 16
    }}>
      <AlertTriangle style={{ width: 40, height: 40, color: "#ef4444" }} />
      <h2 style={{ color: "#fff", fontSize: 20, fontWeight: 700 }}>Could not generate report</h2>
      <p style={{ color: "rgba(255,255,255,0.5)", fontSize: 13, textAlign: "center", maxWidth: 420 }}>
        {message || "An unexpected error occurred. Please try again."}
      </p>
      <Button onClick={onRetry} variant="outline" style={{ display: "flex", gap: 8 }}>
        <RefreshCw className="h-4 w-4" /> Retry
      </Button>
      <Link to="/assessment">
        <Button variant="ghost" style={{ color: "rgba(255,255,255,0.5)" }}>
          Continue Assessment
        </Button>
      </Link>
    </div>
  </div>
);

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------
const AIInsightsPage = () => {
  const navigate = useNavigate();
  const [report, setReport]             = useState(null);
  const [loading, setLoading]           = useState(true);
  const [error, setError]               = useState(null);
  const [expandedPane, setExpandedPane] = useState(null); // null | "ent" | "ven"
  const [refreshing, setRefreshing]     = useState(false);

  const entCompactRef = useRef(null);
  const venCompactRef = useRef(null);
  const entFullRef    = useRef(null);
  const venFullRef    = useRef(null);
  const compactCharts = useRef({ ent: null, ven: null });
  const fullCharts    = useRef({ ent: null, ven: null });

  // ── Fetch ────────────────────────────────────────────────────────────────
  const fetchReport = useCallback(async (forceRefresh = false) => {
    // Redirect immediately if no session token
    if (!apiService.isAuthenticated()) {
      navigate("/login", { replace: true, state: { from: "/ai-insights" } });
      return;
    }
    try {
      setLoading(true);
      setError(null);
      const result = await apiService.getInsightsReport(forceRefresh);
      if (result.success && result.data?.report) {
        setReport(result.data.report);
      } else {
        // 401 / session expired → send to login
        const errMsg = result.error || result.data?.error || "";
        if (/401|unauthorized|not authenticated|session/i.test(errMsg)) {
          navigate("/login", { replace: true, state: { from: "/ai-insights" } });
          return;
        }
        setError(errMsg || "Failed to fetch insights report.");
      }
    } catch (err) {
      setError(err.message || "Network error.");
    } finally {
      setLoading(false);
    }
  }, [navigate]);

  useEffect(() => { fetchReport(false); }, [fetchReport]);

  const handleRefresh = async () => {
    setRefreshing(true);
    await fetchReport(true);
    setRefreshing(false);
  };

  // ── Compact radar charts ──────────────────────────────────────────────────
  useEffect(() => {
    if (!report || expandedPane) return;
    const entSeries = radarVals(report.entrepreneur?.radar, ENT_LABELS);
    const venSeries = radarVals(report.venture?.radar,      VEN_LABELS);

    if (compactCharts.current.ent) compactCharts.current.ent.destroy();
    if (compactCharts.current.ven) compactCharts.current.ven.destroy();

    if (entCompactRef.current) {
      compactCharts.current.ent = new Chart(entCompactRef.current, {
        type: "radar",
        data: {
          labels: ENT_LABELS,
          datasets: [{
            data: entSeries,
            borderColor: "#f97316",
            backgroundColor: "rgba(249,115,22,0.12)",
            pointBackgroundColor: "#f97316",
            pointRadius: 2,
            borderWidth: 1.5,
          }],
        },
        options: radarOptions,
      });
    }
    if (venCompactRef.current) {
      compactCharts.current.ven = new Chart(venCompactRef.current, {
        type: "radar",
        data: {
          labels: VEN_LABELS,
          datasets: [{
            data: venSeries,
            borderColor: "#3b82f6",
            backgroundColor: "rgba(59,130,246,0.12)",
            pointBackgroundColor: "#3b82f6",
            pointRadius: 2,
            borderWidth: 1.5,
          }],
        },
        options: radarOptions,
      });
    }
    return () => {
      if (compactCharts.current.ent) compactCharts.current.ent.destroy();
      if (compactCharts.current.ven) compactCharts.current.ven.destroy();
      compactCharts.current = { ent: null, ven: null };
    };
  }, [report, expandedPane]);

  // ── Full radar (expanded pane only) ──────────────────────────────────────
  useEffect(() => {
    document.body.classList.toggle("ai7-no-scroll", Boolean(expandedPane));
    if (!report) return;

    const entSeries = radarVals(report.entrepreneur?.radar, ENT_LABELS);
    const venSeries = radarVals(report.venture?.radar,      VEN_LABELS);

    if (expandedPane === "ent" && entFullRef.current && !fullCharts.current.ent) {
      fullCharts.current.ent = new Chart(entFullRef.current, {
        type: "radar",
        data: {
          labels: ENT_LABELS,
          datasets: [
            { label: "Your Score",      data: entSeries,   borderColor: "#f97316", backgroundColor: "rgba(249,115,22,0.15)", pointBackgroundColor: "#f97316", pointRadius: 3, borderWidth: 2 },
            { label: "Average Founder", data: AVG_FOUNDER, borderColor: "rgba(255,255,255,0.2)", backgroundColor: "rgba(255,255,255,0.03)", pointBackgroundColor: "rgba(255,255,255,0.3)", pointRadius: 2, borderWidth: 1 },
          ],
        },
        options: { ...radarOptions, plugins: { legend: { display: true, labels: { color: "rgba(255,255,255,0.4)", font: { size: 10 } } } } },
      });
    }
    if (expandedPane === "ven" && venFullRef.current && !fullCharts.current.ven) {
      fullCharts.current.ven = new Chart(venFullRef.current, {
        type: "radar",
        data: {
          labels: VEN_LABELS,
          datasets: [
            { label: "Your Score",      data: venSeries,    borderColor: "#3b82f6", backgroundColor: "rgba(59,130,246,0.15)", pointBackgroundColor: "#3b82f6", pointRadius: 3, borderWidth: 2 },
            { label: "Average Venture", data: AVG_VENTURE,  borderColor: "rgba(255,255,255,0.2)", backgroundColor: "rgba(255,255,255,0.03)", pointBackgroundColor: "rgba(255,255,255,0.3)", pointRadius: 2, borderWidth: 1 },
          ],
        },
        options: { ...radarOptions, plugins: { legend: { display: true, labels: { color: "rgba(255,255,255,0.4)", font: { size: 10 } } } } },
      });
    }
    if (expandedPane !== "ent" && fullCharts.current.ent) { fullCharts.current.ent.destroy(); fullCharts.current.ent = null; }
    if (expandedPane !== "ven" && fullCharts.current.ven) { fullCharts.current.ven.destroy(); fullCharts.current.ven = null; }

    return () => { document.body.classList.remove("ai7-no-scroll"); };
  }, [expandedPane, report]);

  // ── Guards ────────────────────────────────────────────────────────────────
  if (loading)  return <LoadingState />;
  if (error)    return <ErrorState message={error} onRetry={() => fetchReport(false)} />;
  if (!report)  return <ErrorState message="No report data received." onRetry={() => fetchReport(false)} />;

  // ── Derived values ────────────────────────────────────────────────────────
  const ent       = report.entrepreneur || {};
  const ven       = report.venture      || {};
  const align     = report.alignment    || {};
  const readiness = report.readiness    || {};
  const consensus = report.consensus    || {};

  const entScore  = ent.score   ?? 0;
  const venScore  = ven.score   ?? 0;
  const aliScore  = align.score ?? 0;
  const combined  = align.combined_score ?? Math.round((entScore + venScore) / 2);

  const entSeries = radarVals(ent.radar, ENT_LABELS);
  const venSeries = radarVals(ven.radar, VEN_LABELS);

  const entPhases = ent.phases  || [];
  const venPhases = ven.phases  || [];

  const sweet     = align.sweet_spots       || [];
  const risks     = align.risk_zones        || [];
  const untapped  = align.untapped_potential || [];

  const isUnlocked = readiness.unlocked ??
    (entScore >= (readiness.entrepreneur_target ?? 75) &&
     venScore >= (readiness.venture_target    ?? 70)   &&
     aliScore >= (readiness.alignment_target  ?? 60));

  const entDimBars = ENT_LABELS.map((l, i) => ({ label: l, value: entSeries[i] })).sort((a, b) => b.value - a.value);
  const venDimBars = VEN_LABELS.map((l, i) => ({ label: l, value: venSeries[i] })).sort((a, b) => b.value - a.value);

  const makePills = (phases) =>
    phases.map((p) => ({
      label: p.title?.replace("Phase ", "P") || p.id,
      state: p.completed ? "done" : p.score != null ? "progress" : "locked",
    }));

  return (
    <div className="ai7-page">
      <div className="ai7-bg" />
      <div className="ai7-container">

        {/* ── HEADER ────────────────────────────────────────── */}
        {!expandedPane && (
          <header className="ai7-header">
            <h1>
              Your AI Insights — <span className="o">Entrepreneur</span> &amp; <span className="b">Venture</span>
            </h1>
            <p style={{ color: "rgba(255,255,255,0.4)", fontSize: 12, marginTop: 4 }}>
              {consensus.responses_analyzed
                ? `Based on ${consensus.responses_analyzed} responses · ${consensus.phases_analyzed ?? "?"} phases`
                : "Based on your assessment data"}
              {report.generated_at && ` · ${new Date(report.generated_at).toLocaleDateString("en-US", { day: "numeric", month: "long", year: "numeric" })}`}
            </p>
            <div className="ai7-combined">
              <div>
                <div className="ai7-combined-score">{combined}</div>
                <div className="ai7-combined-label">Combined Score</div>
              </div>
              <div className="ai7-divider" />
              <div className="ai7-align">
                Alignment: <b style={{ color: "#a855f7" }}>{aliScore}%</b>
              </div>
              <div className="ai7-divider" />
              <button
                onClick={handleRefresh}
                disabled={refreshing}
                style={{
                  background: "none", border: "1px solid rgba(255,255,255,0.1)",
                  borderRadius: 6, padding: "4px 10px", cursor: refreshing ? "not-allowed" : "pointer",
                  color: "rgba(255,255,255,0.5)", fontSize: 11,
                  display: "flex", alignItems: "center", gap: 4,
                }}
              >
                <RefreshCw className={`h-3 w-3 ${refreshing ? "animate-spin" : ""}`} />
                {refreshing ? "Regenerating…" : "Regenerate"}
              </button>
            </div>
          </header>
        )}

        {/* ── PANES ─────────────────────────────────────────── */}
        <section className={`ai7-panes ${expandedPane ? "is-expanded" : ""}`}>

          {/* ── ENTREPRENEUR ──────────────────────────────────── */}
          <article className={`ai7-pane ent ${expandedPane === "ent" ? "expanded" : ""} ${expandedPane === "ven" ? "collapsed" : ""}`}>
            <div className="ai7-pane-head" onClick={() => !expandedPane && setExpandedPane("ent")}>
              <div>
                <small>Entrepreneur Profile</small>
                <h3>{ent.tagline || "The Founder"}</h3>
              </div>
              <div className="ai7-score ent">{entScore}</div>
            </div>

            {!expandedPane && (
              <>
                <div className="ai7-grid">
                  <div className="ai7-card">
                    <div className="ai7-label">Skills Radar</div>
                    <canvas ref={entCompactRef} />
                  </div>
                  <div className="ai7-card">
                    <div className="ai7-label">Key Dimensions</div>
                    <div className="ai7-mini-bars">
                      {entDimBars.slice(0, 6).map((d) => (
                        <MiniBar key={d.label} label={d.label} value={d.value} colorClass="ent" />
                      ))}
                    </div>
                  </div>
                  {ent.strengths?.length > 0 && (
                    <div className="ai7-card">
                      <div className="ai7-label">Strengths</div>
                      {ent.strengths.slice(0, 3).map((s) => (
                        <div key={s.name} className="str-row">
                          <span className="str-dot green" />
                          <span className="s-name">{s.name}</span>
                          <span className="s-val">{s.score}</span>
                        </div>
                      ))}
                    </div>
                  )}
                  {ent.growth_areas?.length > 0 && (
                    <div className="ai7-card">
                      <div className="ai7-label">Growth Areas</div>
                      {ent.growth_areas.slice(0, 3).map((g) => (
                        <div key={g.name} className="str-row">
                          <span className="str-dot red" />
                          <span className="s-name">{g.name}</span>
                          <span className="s-val">{g.score}</span>
                        </div>
                      ))}
                    </div>
                  )}
                  <div className="ai7-card card-wide">
                    <div className="ai7-label">Assessment Progress</div>
                    <div className="phase-pills">
                      {makePills(entPhases).map((p) => (
                        <span key={p.label} className={`phase-pill ${p.state}`}>{p.label}</span>
                      ))}
                    </div>
                    <div style={{ marginTop: 8 }}>
                      <MiniBar
                        label="Completion"
                        value={Math.round(entPhases.filter((p) => p.completed).length / Math.max(entPhases.length, 1) * 100)}
                        colorClass="ent"
                      />
                    </div>
                  </div>
                </div>
                {ent.recent_activity?.length > 0 && (
                  <div className="ai7-card card-wide" style={{ marginTop: 0 }}>
                    <div className="ai7-label">Recent Activity</div>
                    <div className="act-list">
                      {ent.recent_activity.slice(0, 3).map((act, i) => {
                        const iconMap = { completed: { icon: "✓", cls: "green" }, progress: { icon: "◐", cls: "orange" }, unlocked: { icon: "★", cls: "purple" } };
                        const { icon, cls } = iconMap[act.type] || { icon: "•", cls: "orange" };
                        return (
                          <div key={i} className="act-item">
                            <div className={`act-icon ${act.color || cls}`}>{act.icon || icon}</div>
                            <span className="act-text" dangerouslySetInnerHTML={{ __html: act.text || act.label || "" }} />
                          </div>
                        );
                      })}
                    </div>
                  </div>
                )}
                <button className="ai7-expand-btn" onClick={() => setExpandedPane("ent")}>
                  Click to expand full profile →
                </button>
              </>
            )}

            {expandedPane === "ent" && (
              <div className="ai7-expanded">
                <button className="back-btn" onClick={() => setExpandedPane(null)}>← Back to Dashboard</button>
                {ent.summary && (
                  <div className="exp-section">
                    <div style={{ background: "rgba(249,115,22,0.06)", border: "1px solid rgba(249,115,22,0.15)", borderRadius: 12, padding: "16px 20px", color: "rgba(255,255,255,0.65)", fontSize: 13, lineHeight: 1.7 }}>
                      <b style={{ color: "#f97316" }}>{ent.archetype}</b>{ent.archetype ? " — " : ""}{ent.summary}
                    </div>
                  </div>
                )}
                <div className="exp-section">
                  <h3>Your Entrepreneur Radar</h3>
                  <p className="exp-sub">All 12 entrepreneur dimensions vs. average assessed founder</p>
                  <div className="ai7-full-radar"><canvas ref={entFullRef} /></div>
                </div>
                {entPhases.map((phase) => (
                  <div key={phase.id} className="exp-section">
                    <div className="exp-phase-header">
                      <span className="eph-icon">{phase.icon || "📋"}</span>
                      <h3>{phase.title}</h3>
                      <span className="eph-score" style={{ color: phase.score != null ? scoreColor(phase.score) : "rgba(255,255,255,0.3)" }}>
                        {phase.score ?? "—"}
                      </span>
                    </div>
                    {(!phase.completed && !phase.cards?.length) ? (
                      <div className="locked-phase">
                        🔒 Phase Not Started
                        <br /><span style={{ fontSize: 12 }}>Complete this phase to see detailed analysis.</span>
                        <br /><Link to="/assessment" className="lock-btn">Begin Phase →</Link>
                      </div>
                    ) : (
                      <div className="exp-grid">
                        {(phase.cards || []).map((card) => (
                          <PhaseCard key={card.name} card={card} accent="#f97316" />
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </article>

          {/* ── VENTURE ───────────────────────────────────────── */}
          <article className={`ai7-pane ven ${expandedPane === "ven" ? "expanded" : ""} ${expandedPane === "ent" ? "collapsed" : ""}`}>
            <div className="ai7-pane-head" onClick={() => !expandedPane && setExpandedPane("ven")}>
              <div>
                <small>Venture Profile</small>
                <h3>{ven.tagline || "The Idea"}</h3>
              </div>
              <div className="ai7-score ven">{venScore}</div>
            </div>

            {!expandedPane && (
              <>
                <div className="ai7-grid">
                  <div className="ai7-card">
                    <div className="ai7-label">Venture Radar</div>
                    <canvas ref={venCompactRef} />
                  </div>
                  <div className="ai7-card">
                    <div className="ai7-label">Key Dimensions</div>
                    <div className="ai7-mini-bars">
                      {venDimBars.slice(0, 6).map((d) => (
                        <MiniBar key={d.label} label={d.label} value={d.value} colorClass="ven" />
                      ))}
                    </div>
                  </div>
                  {ven.validation_pct != null && (
                    <div className="ai7-card">
                      <div className="ai7-label">Validation Status</div>
                      <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                        {/* Donut */}
                        <div style={{ position: "relative", width: 72, height: 72, flexShrink: 0 }}>
                          {(() => {
                            const pct = ven.validation_pct;
                            const circ = 2 * Math.PI * 30;
                            const offset = circ - (pct / 100) * circ;
                            return (
                              <svg viewBox="0 0 72 72" style={{ width: 72, height: 72, transform: "rotate(-90deg)" }}>
                                <circle cx="36" cy="36" r="30" fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth={6} />
                                <circle cx="36" cy="36" r="30" fill="none" stroke="#3b82f6" strokeWidth={6}
                                  strokeLinecap="round" strokeDasharray={circ} strokeDashoffset={offset}
                                  style={{ filter: "drop-shadow(0 0 6px rgba(59,130,246,0.4))" }} />
                              </svg>
                            );
                          })()}
                          <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%,-50%)", textAlign: "center" }}>
                            <div style={{ fontSize: 14, fontWeight: 800, color: "#fff" }}>{ven.validation_pct}%</div>
                            <div style={{ fontSize: 7, color: "rgba(255,255,255,0.4)", letterSpacing: 0.5 }}>VALID</div>
                          </div>
                        </div>
                        {/* Mini bars */}
                        <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: 6 }}>
                          {[
                            { label: "Interviews", done: ven.interviews_done ?? 0, target: ven.interviews_target ?? 20, color: "#3b82f6" },
                            { label: "Competitors", done: ven.competitors_validated ?? 0, target: ven.competitors_target ?? 5, color: "#f97316" },
                          ].map(({ label, done, target, color }) => (
                            <div key={label}>
                              <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: "rgba(255,255,255,0.4)", marginBottom: 3 }}>
                                <span>{label}</span>
                                <span style={{ color: "rgba(255,255,255,0.6)", fontWeight: 600 }}>{done}/{target}</span>
                              </div>
                              <div style={{ height: 4, background: "rgba(255,255,255,0.06)", borderRadius: 2, overflow: "hidden" }}>
                                <div style={{ height: 4, width: `${Math.min(100, (done / target) * 100)}%`, background: color, borderRadius: 2 }} />
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}
                  {ven.runway_months != null && (
                    <div className="ai7-card">
                      <div className="ai7-label">Runway Health</div>
                      <div style={{ textAlign: "center", marginBottom: 8 }}>
                        <div style={{ fontSize: 24, fontWeight: 800, color: "#fff" }}>
                          {ven.runway_months}<span style={{ fontSize: 12, color: "rgba(255,255,255,0.4)", fontWeight: 400 }}>mo</span>
                        </div>
                        <div style={{ fontSize: 10, color: "rgba(255,255,255,0.3)" }}>Available Runway</div>
                      </div>
                      {ven.months_to_profit != null && (
                        <>
                          <div style={{ textAlign: "center", marginBottom: 4 }}>
                            <div style={{ fontSize: 16, fontWeight: 700, color: ven.months_to_profit > ven.runway_months ? "#ef4444" : "#22c55e" }}>
                              {ven.months_to_profit}mo <span style={{ fontSize: 11, opacity: 0.6 }}>needed</span>
                            </div>
                            <div style={{ fontSize: 10, color: "rgba(255,255,255,0.3)" }}>Est. Time to Profit</div>
                          </div>
                          {ven.months_to_profit > ven.runway_months && (
                            <div style={{ fontSize: 11, color: "#ef4444", fontWeight: 600, textAlign: "center" }}>
                              Gap: {ven.months_to_profit - ven.runway_months}mo
                            </div>
                          )}
                        </>
                      )}
                    </div>
                  )}
                  {ven.heatmap && (() => {
                    const rows = ["Strategic", "Behavioral", "Predictive"];
                    const cols = ["Model", "Strategy", "Market", "Valid.", "Compet.", "Sizing"];
                    const heatColor = (v) => v >= 70 ? "rgba(34,197,94,0.25)" : v >= 55 ? "rgba(249,115,22,0.2)" : "rgba(239,68,68,0.2)";
                    return (
                      <div className="ai7-card card-wide">
                        <div className="ai7-label">Market Traction Heatmap</div>
                        <div className="heatmap">
                          <div className="h-head" />
                          {cols.map((c) => <div key={c} className="h-head">{c}</div>)}
                          {rows.map((row) => (
                            <React.Fragment key={row}>
                              <div className="h-label">{row}</div>
                              {(ven.heatmap[row] || []).map((val, ci) => (
                                <div key={ci} className="h-cell" style={{ background: heatColor(val) }}>{val}</div>
                              ))}
                            </React.Fragment>
                          ))}
                        </div>
                      </div>
                    );
                  })()}
                  <div className="ai7-card card-wide">
                    <div className="ai7-label">Assessment Progress</div>
                    <div className="phase-pills">
                      {makePills(venPhases).map((p) => (
                        <span key={p.label} className={`phase-pill ${p.state}`}>{p.label}</span>
                      ))}
                    </div>
                    <div style={{ marginTop: 8 }}>
                      <MiniBar
                        label="Completion"
                        value={Math.round(venPhases.filter((p) => p.completed).length / Math.max(venPhases.length, 1) * 100)}
                        colorClass="ven"
                      />
                    </div>
                  </div>
                </div>
                <button className="ai7-expand-btn" onClick={() => setExpandedPane("ven")}>
                  Click to expand full profile →
                </button>
              </>
            )}

            {expandedPane === "ven" && (
              <div className="ai7-expanded">
                <button className="back-btn" onClick={() => setExpandedPane(null)}>← Back to Dashboard</button>
                {ven.summary && (
                  <div className="exp-section">
                    <div style={{ background: "rgba(59,130,246,0.06)", border: "1px solid rgba(59,130,246,0.15)", borderRadius: 12, padding: "16px 20px", color: "rgba(255,255,255,0.65)", fontSize: 13, lineHeight: 1.7 }}>
                      <b style={{ color: "#3b82f6" }}>{ven.idea_name}</b>{ven.idea_name ? " — " : ""}{ven.summary}
                    </div>
                  </div>
                )}
                <div className="exp-section">
                  <h3>Your Venture Radar</h3>
                  <p className="exp-sub">All 8 venture dimensions vs. average assessed venture</p>
                  <div className="ai7-full-radar"><canvas ref={venFullRef} /></div>
                </div>
                {venPhases.map((phase) => (
                  <div key={phase.id} className="exp-section">
                    <div className="exp-phase-header">
                      <span className="eph-icon">{phase.icon || "📊"}</span>
                      <h3>{phase.title}</h3>
                      <span className="eph-score" style={{ color: phase.score != null ? scoreColor(phase.score) : "rgba(255,255,255,0.3)" }}>
                        {phase.score ?? "—"}
                      </span>
                    </div>
                    {(!phase.completed && !phase.cards?.length) ? (
                      <div className="locked-phase">
                        🔒 Phase Not Started
                        <br /><span style={{ fontSize: 12 }}>Complete this phase to unlock detailed analysis.</span>
                        <br /><Link to="/assessment" className="lock-btn">Begin Phase →</Link>
                      </div>
                    ) : (
                      <div className="exp-grid">
                        {(phase.cards || []).map((card) => (
                          <PhaseCard key={card.name} card={card} accent="#3b82f6" />
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </article>
        </section>

        {/* ── CONNECTING THE DOTS ───────────────────────────── */}
        {!expandedPane && (
          <section className="alignment-section">
            <div className="section-divider">
              <div className="div-line" />
              <div className="div-label">Connecting the Dots</div>
              <div className="div-line" />
            </div>

            <div className="align-header">
              <h2>
                Where <span className="o">You</span> and <span className="b">Your Idea</span>{" "}
                <span className="p">Align</span>
              </h2>
              <p className="ah-sub">
                AI cross-references your entrepreneur profile with your venture profile to uncover
                where your personal traits reinforce your business — and where dangerous gaps exist.
              </p>
            </div>

            <div className="align-overview">
              <div className="ao-pillar">
                <div className="ao-tag orange">Entrepreneur</div>
                <div className="ao-big orange">{entScore}</div>
                <div className="ao-name">{ent.tagline || "The Founder"}</div>
              </div>
              <div className="ao-center">
                <div className="ao-venn">
                  <div className="venn-circle left" />
                  <div className="venn-circle right" />
                  <div className="venn-score">
                    <div className="vs-num">{aliScore}%</div>
                    <div className="vs-label">Alignment</div>
                  </div>
                </div>
                <div className="ao-stats">
                  <div className="ao-stat"><div className="as-num green">{sweet.length}</div><div className="as-label">Sweet Spots</div></div>
                  <div className="ao-stat"><div className="as-num red">{risks.length}</div><div className="as-label">Risk Zones</div></div>
                  <div className="ao-stat"><div className="as-num purple">{untapped.length}</div><div className="as-label">Untapped</div></div>
                </div>
              </div>
              <div className="ao-pillar">
                <div className="ao-tag blue">Venture</div>
                <div className="ao-big blue">{venScore}</div>
                <div className="ao-name">{ven.tagline || "The Idea"}</div>
              </div>
            </div>

            {sweet.length > 0 && (
              <>
                <div className="cat-header">
                  <span className="ch-icon">✦</span>
                  <h3 style={{ color: "#22c55e" }}>Sweet Spots — Where You Reinforce Your Venture</h3>
                  <span className="ch-count">{sweet.length} found</span>
                </div>
                {sweet.map((item, i) => <ConnCard key={i} item={item} type="sweet" />)}
              </>
            )}

            {risks.length > 0 && (
              <>
                <div className="cat-header" style={{ marginTop: 32 }}>
                  <span className="ch-icon">⚠</span>
                  <h3 style={{ color: "#ef4444" }}>Risk Zones — Where Gaps Compound</h3>
                  <span className="ch-count">{risks.length} detected</span>
                </div>
                {risks.map((item, i) => <ConnCard key={i} item={item} type="risk" />)}
              </>
            )}

            {untapped.length > 0 && (
              <>
                <div className="cat-header" style={{ marginTop: 32 }}>
                  <span className="ch-icon">💎</span>
                  <h3 style={{ color: "#a855f7" }}>Untapped Potential — Strengths You Haven't Leveraged Yet</h3>
                  <span className="ch-count">{untapped.length} identified</span>
                </div>
                {untapped.map((item, i) => <ConnCard key={i} item={item} type="potential" />)}
              </>
            )}

            {/* Readiness meter */}
            <div className="readiness">
              <h3>🔓 Business Builder Readiness</h3>
              <p className="r-sub">When all three targets are met, our AI will design your actual business components</p>
              <div className="readiness-bars">
                {[
                  { label: "Entrepreneur Score", value: entScore, target: readiness.entrepreneur_target ?? 75, colorClass: "orange" },
                  { label: "Venture Score",       value: venScore, target: readiness.venture_target    ?? 70, colorClass: "blue"   },
                  { label: "Alignment Score",     value: aliScore, target: readiness.alignment_target  ?? 60, colorClass: "purple", suffix: "%" },
                ].map(({ label, value, target, colorClass, suffix = "" }) => (
                  <div key={label} className="r-item">
                    <div className={`r-label ${colorClass}`}>{label}</div>
                    <div className="r-bar"><div className={`r-fill ${colorClass}`} style={{ width: `${value}%` }} /></div>
                    <div className="r-vals">
                      <span className="r-current">{value}{suffix}</span>
                      <span className="r-target">Target: {target}{suffix}</span>
                    </div>
                    <div className={`r-check ${value >= target ? "pass" : "fail"}`}>
                      {value >= target ? `✓ Passed` : `✗ ${target - value}${suffix} to go`}
                    </div>
                  </div>
                ))}
              </div>
              <div className={`unlock-msg ${isUnlocked ? "unlocked" : "locked"}`}>
                {isUnlocked
                  ? "🎉 Business Builder unlocked! All three targets met."
                  : `🔒 ${readiness.unlock_message || "Improve your scores across all three dimensions to unlock the Business Builder."}`}
              </div>
            </div>

            {/* AI consensus attribution */}
            {consensus.models?.length > 0 && (
              <div style={{ textAlign: "center", marginTop: 24, fontSize: 11, color: "rgba(255,255,255,0.2)", letterSpacing: 0.5 }}>
                AI Consensus ·{" "}
                {consensus.models.map((m) => `${m.provider || ""}/${m.model || ""}`.replace(/^\//, "")).join(" · ")}
                {" "}· Confidence {Math.round((consensus.confidence ?? 1) * 100)}%
                {report._from_cache && " · cached"}
              </div>
            )}
          </section>
        )}

        {/* ── FOOTER ────────────────────────────────────────── */}
        {!expandedPane && (
          <footer style={{ display: "flex", gap: 12, justifyContent: "center", padding: "0 0 40px" }}>
            <Link to="/dashboard"><Button>Back to Dashboard</Button></Link>
            <Link to="/assessment"><Button variant="outline">Continue Assessment</Button></Link>
          </footer>
        )}
      </div>
    </div>
  );
};

export default AIInsightsPage;
